[package]
name = "raden"
version = "2026.0.0"
edition = "2024"
rust-version = "1.88"
authors = ["Shiguredo Inc."]
license = "Apache-2.0"
description = "2D Vector Graphics Library"
homepage = "https://github.com/shiguredo/raden"
repository = "https://github.com/shiguredo/raden"
readme = "README.md"

[dependencies]
cranelift-codegen = "=0.128.3"
cranelift-frontend = "=0.128.3"
cranelift-jit = "=0.128.3"
cranelift-module = "=0.128.3"
cranelift-native = "=0.128.3"

[dev-dependencies]
raw_player = "2026.1.0-canary.0"

[workspace]
members = ["pbt"]
exclude = ["fuzz"]
